import streamlit as st
import requests

st.set_page_config(page_title="Brain Tumor Detection")

st.title("🧠 Brain Tumor Classification System")

with st.expander("📋 Image Upload Guidelines"):

    st.markdown("✅ Upload a brain MRI image only")

    st.markdown("✅ Ensure the brain region is clearly visible")

    st.markdown("✅ Use images similar to clinical MRI scans")

    st.markdown("✅ Supported formats: JPG, JPEG, PNG")

    st.markdown("❌ Do not upload screenshots or edited images")

    st.markdown("❌ Avoid blurry or low-resolution images")

    st.markdown("⚠️ Images significantly different from the training data may produce unreliable predictions")

uploaded_file = st.file_uploader(
    "Upload MRI Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    st.image(uploaded_file, caption="Uploaded MRI", use_container_width=True)

    if st.button("Predict"):

        files = {
            "file": uploaded_file.getvalue()
        }

        response = requests.post(
            "https://brain-tumor-classification-system-1.onrender.com/predict",
            files={"file": uploaded_file}
        )

        st.write("Status Code:", response.status_code)
        st.write("Response:", response.text)

        result = response.json()

        st.success(
            f"Prediction: {result['prediction']}"
        )

        st.metric(
            "Confidence Score",
            f"{result['confidence']}%"
        )

        status = result["status"]

        if "Reliable" in status:
            st.success(f"🟢 {status}")

        elif "acceptable" in status.lower():
            st.warning(f"🟡 {status}")

        else:
            st.error(f"🔴 {status}")

        st.subheader("Probability Breakdown")

        for tumor_type, prob in result["probabilities"].items():
            st.write(f"{tumor_type.replace('_', ' ').title()} - {prob}%")
            st.progress(prob / 100)


with st.expander("Model Information"):
    st.write("Architecture: EfficientNet-B0")
    st.write("Framework: PyTorch")
    st.write("Classes: Glioma, Meningioma, Pituitary, No Tumor")


st.info(
    """
    ⚠️ Disclaimer

    This system is intended for educational and research purposes only.

    Predictions generated by this AI model should not be considered a medical diagnosis and must be verified by qualified healthcare professionals.
    """
)
